name: Auto Datamine Pipeline

on:
  push:
    paths:
      - 'auto_pipeline.py'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install requests beautifulsoup4
      - name: Run Script
        run: python auto_pipeline.py
