name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests Pillow

      - name: Run pipeline script
        run: python wtm_pipeline_final_complete.py
